apiRules:
- exclude:
    uidRegex: ^System\.
    type: Namespace
- exclude:
    uidRegex: ^Microsoft\.
    type: Namespace
- exclude:
    uidRegex: \.Tests?\.
    type: Namespace
- exclude:
    uidRegex: \.Examples?\.
    type: Namespace