apiRules:
- exclude:
    uidRegex: ^System\.
    type: Namespace
- exclude:
    uidRegex: ^Microsoft\.
    type: Namespace
- exclude:
    uidRegex: \.Tests?\.
    type: Namespace
- exclude:
    uidRegex: \.Examples?\.
    type: Namespace
- exclude:
    uidRegex: \.SourceGenerator\.
    type: Namespace
- exclude:
    uidRegex: Handlr\.SourceGenerator
    type: Namespace